<?php

return [
    'permission' => ['ACP-system-control',
        'ACP-view',
        'ACP-user-list-view',
        'ACP-user-edit',
        'ACP-user-update',
        'ACP-user-edit-avatar',
        'ACP-user-edit-password',
        'ACP-user-delete',
        'ACP-user-view',
        'ACP-role-list-view',
        'ACP-role-edit',
        'ACP-role-create',
        'ACP-role-update',
        'MOD-add-new-post',
        'MOD-edit-post',
        'ACP-role-delete',
        'ACP-permission-list-view',
        'ACP-permission-edit',
        'MOD-info-my-exists',
        'ACP-permission-create',
        'ACP-permission-delete',
        'USER-locked',
        'ACP-permission-update',
        'USER-login',],
    'role' => ['Owner',
        'admin',
        'user'],
    ];
